stages:
  - build_front
  - install_back

# npm install Back
install_back:
  stage: install_back
  cache:
    - key:
        files: [ ./package-lock.json ]
      paths:   [ ./node_modules/ ]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_PIPELINE_SOURCE != "merge_request_event"'
      when: manual
  tags:
    - nodejs-20
  variables:
    # NODE_ENV: development
    NODE_ENV: production
  script:
    # - test -r ../node_modules.1.tar.gz && tar -xvf ../node_modules.1.tar.gz
    - npm install

# npm install Front + build Front
build_front:
  stage: build_front
  rules:
    - if: '$CI_COMMIT_BRANCH == "release"'
      when: always
    - if: '$CI_COMMIT_BRANCH != "release"'
      when: manual  
  tags:
    - nodejs-20
  cache:
    - key:
        files: [ ./front/package-lock.json ]
      paths: [ ./front/node_modules/ ]
  variables:
    # NODE_ENV: development
    NODE_ENV: production
    PUBLIC_URL: 68064ef1-1e5c-4384-8c50-626f52b78c5c
    REACT_APP_TAG: dee007ae-5efd-45d8-b81c-86e440522b55
  script:
    - cd front
    - tar -xf ~/rudi-console-proxy_front.cache.tar.xz
    - npm install
    - npm run build
  artifacts:
    name: 'ProdManager-front-$PUBLIC_URL-rev$CI_COMMIT_SHORT_SHA'
    paths:
      - front/build/
      - front/node_modules/
    expire_in: 1 weeks
