stages:
  - npm_install
  - test
  - quality

# This folder is cached between builds
cache:
  paths:
    - node_modules/
    - front/node_modules/

back_npm:
  stage: npm_install
  tags:
    - nodejs
  script:
    - npm install

front_npm:
  stage: npm_install
  tags:
    - nodejs
  script:
    - cd front && npm install

back_test:
  stage: test
  tags:
    - nodejs
  script:
    - 'npm run testCI'
  allow_failure: true
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

lint:
  stage: quality
  tags:
    - nodejs
  script:
    - npm run lint
