; local config file for RUDI API module

[server]
listening_address = 0.0.0.0
listening_port = 5000

[database]
db_url = TODO
db_name = TODO

[API_RUDI]
## listening_address = http://localhost:3001
listening_address = https://shared-rudi.aqmo.org/api/v1
listening_port = deprecated

[logging]
app_name = rudiConsoleProxy
log_dir = ./logs
log_file = rudiConsoleProxy.log
