; local config file for Prod Manager module
;
; [ IMPORTANT NOTICE ]
; the config parameters values are read if and only if the parameters 
; names appear in the list of loaded parameters in the file config/config.js
; 

[server]
listening_address = 0.0.0.0
listening_port = 5000

[auth]
; key for the frontend communication with backend
secret_key_JWT = "secret_key_to_change"
; tokens expiration time in seconds
exp_time_s = 1200

[security]
; helmet conf: frontend can only make calls to trusted domains (and itself)
trusted_domain[] = https://data-rudi.aqmo.org
trusted_domain[] = https://shared-rudi.aqmo.org
trusted_domain[] = https://admin-rudi.aqmo.org

[database]
db_directory = "./db"
db_filename = "rudy_manager.db"

[API_RUDI]
## listening_address = http://localhost:3001
listening_address = https://shared-rudi.aqmo.org
admin_api = /api/admin
RUDI_key = "./env/ed25519_rudiprogmanager-shared"
api_key = "./env/ed25519_rudiprogmanager-shared"
manager_id = "rudi_prod_manager_shared"
exp_time_s = 1200

[rudi_media]
media_url = https://shared-rudi.aqmo.org/media/
media_key = "./env/ed25519_rudiprogmanager-shared"
manager_id = "rudimanager"
default_client_group = "producer"
exp_time_s = 1200

[formulaire]
base_url = https://admin-rudi.aqmo.org/shared/

[logging]
app_name = rudiProdManagerBack
log_dir = ./logs/
log_file = rudiProdManagerBack.log

[syslog]
; sets the lowest priority level of the logs written
syslog_level = debug
; syslog conf
syslog_host = localhost
syslog_port = 514
syslog_facility = local4
syslog_protocol = unix
; Available values: bsd | 3164 | RFC3164 | 5424 | RFC5424
syslog_type = RFC5424
; full path of the socket to which syslog messages should be sent
; unix: /dev/log
; macOS: /var/run/syslog
syslog_socket = /dev/log
; name of this machine
syslog_node_name = dev
; folder for syslog backup files
syslog_dir = /tmp/devLogs/rudi
