; local config file for Prod Manager module

[server]
listening_address = 0.0.0.0
listening_port = 5000
secret_key_JWT = "secret_key_to_change"

[database]
db_directory = "./db"

[API_RUDI]
## listening_address = http://localhost:3001
listening_address = https://shared-rudi.aqmo.org/api/v1
listening_port = deprecated
admin_api = https://shared-rudi.aqmo.org/api/admin
## media_api = https://data-rudi.aqmo.org/media
media_api = https://shared-rudi.aqmo.org/media


[formulaire]
base_url = https://admin-rudi.aqmo.org/shared/


[logging]
app_name = rudiConsoleProxy
log_dir = ./logs
log_file = rudiConsoleProxy.log
